foo:
  bar: "Some modifications again again and again"
# yq -yi '.spec.template.spec.containers[0].image = "927161.sed.saa.mx-east-2.tinny.com/ead-backend:jua1soq0"' 'some.yml' && yq -yi 'del(select(.kind == "Service") | .spec.template)' 'some.yml'
