name: Hola mundo
run-name: Aprendiendo a implementar GitHub Actions!
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  execute_main:
    name: Ejecutar main.go e imprimir en consola su output.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Golang
        uses: actions/setup-go@v6.0.0
        with:
          go-version-file: './go.mod'
      - name: Running main.go
        run: go run ./main.go
      - name: Set something
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.foo.bar' = "cooler" 'config.yml'
      - name: Outputs new curso-github-actions/config.yml content
        run: cat curso-github-actions/config.yml
